//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vxupkizork-sgmtkzoi-pkrrehkgt-zxgototm-644[kotgr]
        ///mbiyqoxsm-pvygob-nocsqx-900[obmqs]
        ///veqtekmrk-ikk-hitpscqirx-334[nrtws]
        ///gvcskirmg-fyrrc-irkmriivmrk-932[rikmc]
        ///xmtjbzidx-xviyt-yzqzgjkhzio-187[yzfeu]
        ///bwx-amkzmb-kivlg-kwibqvo-lmaqov-798[bkmva]
        ///vcibutulxiom-ohmnuvfy-yaa-mylpcwym-890[iyaun]
        ///ajvyjprwp-lqxlxujcn-jwjuhbrb-251[muivb]
        ///szfyrqriuflj-avccpsvre-kirzezex-971[rezcf]
        ///kwvacumz-ozilm-akidmvomz-pcvb-uizsmbqvo-590[uslyz]
        ///ucynmlgxcb-afmamjyrc-jmegqrgaq-626[rybxt]
        ///oaxadrgx-pkq-abqdmfuaze-872[xtbnw]
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventFour {
            get {
                return ResourceManager.GetString("AdventFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaaaa-bbb-z-y-x-123[abxyz]
        ///a-b-c-d-e-f-g-h-987[abcde]
        ///not-a-real-room-404[oarel]
        ///totally-real-room-200[decoy].
        /// </summary>
        internal static string AdventFourTest {
            get {
                return ResourceManager.GetString("AdventFourTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2, L5, L4, L5, R4, R1, L4, R5, R3, R1, L1, L1, R4, L4, L1, R4, L4, R4, L3, R5, R4, R1, R3, L1, L1, R1, L2, R5, L4, L3, R1, L2, L2, R192, L3, R5, R48, R5, L2, R76, R4, R2, R1, L1, L5, L1, R185, L5, L1, R5, L4, R1, R3, L4, L3, R1, L5, R4, L4, R4, R5, L3, L1, L2, L4, L3, L4, R2, R2, L3, L5, R2, R5, L1, R1, L3, L5, L3, R4, L4, R3, L1, R5, L3, R2, R4, R2, L1, R3, L1, L3, L5, R4, R5, R2, R2, L5, L3, L1, L1, L5, L2, L3, R3, R3, L3, L4, L5, R2, L1, R1, R3, R4, L2, R1, L1, R3, R3, L4, L2, R5, R5, L1, R4, L5, L5, R1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventOne {
            get {
                return ResourceManager.GetString("AdventOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     4   21  894
        ///  419  794  987
        ///  424  797  125
        ///  651  305  558
        ///  655  631  963
        ///    2  628  436
        ///  736   50  363
        ///  657  707  408
        ///  252  705   98
        ///  532  173  878
        ///  574  792  854
        ///  157  737  303
        ///  468   76  580
        ///  502  503  434
        ///  467  567  310
        ///  911  911  391
        ///  791  913  925
        ///  174   49  532
        ///  796  803  426
        ///  800  132  710
        ///  273  722  711
        ///  388  576  551
        ///   17  936  676
        ///  371  712  141
        ///  692  738  913
        ///  745  805  975
        ///  381  140  680
        ///  859  344  336
        ///  109  148  877
        ///  835  441  716
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventThree {
            get {
                return ResourceManager.GetString("AdventThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     4   21  894
        ///  419  794  987
        ///  424  797  125
        ///  651  305  558
        ///  655  631  963
        ///    2  628  436.
        /// </summary>
        internal static string AdventThreeTest {
            get {
                return ResourceManager.GetString("AdventThreeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUURRDRRURUUUDLRUDDLLLURULRRLDULDRDUULULLUUUDRDUDDURRULDRDDDUDDURLDLLDDRRURRUUUDDRUDDLLDDDURLRDDDULRDUDDRDRLRDUULDLDRDLUDDDLRDRLDLUUUDLRDLRUUUDDLUURRLLLUUUUDDLDRRDRDRLDRLUUDUDLDRUDDUDLLUUURUUDLULRDRULURURDLDLLDLLDUDLDRDULLDUDDURRDDLLRLLLLDLDRLDDUULRDRURUDRRRDDDUULRULDDLRLLLLRLLLLRLURRRLRLRDLULRRLDRULDRRLRURDDLDDRLRDLDRLULLRRUDUURRULLLRLRLRRUDLRDDLLRRUDUDUURRRDRDLDRUDLDRDLUUULDLRLLDRULRULLRLRDRRLRLULLRURUULRLLRRRDRLULUDDUUULDULDUDDDUDLRLLRDRDLUDLRLRRDDDURUUUDULDLDDLDRDDDLURLDRLDURUDRURDDDDDDULLDLDLU
        ///LURLRUU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventTwo {
            get {
                return ResourceManager.GetString("AdventTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULL
        ///RRDDD
        ///LURDL
        ///UUUUD.
        /// </summary>
        internal static string AdventTwoTest {
            get {
                return ResourceManager.GetString("AdventTwoTest", resourceCulture);
            }
        }
    }
}
